fancy log

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -53,8 +53,21 @@ documentation:
     cd "$tmpdir"
     export ANSIBLE_COLLECTIONS_PATH="$tmpdir/collections"
     ansible-doc --metadata-dump unity.general | jq '.all | with_entries(select(.key != "keyword" and (.value | keys | length) > 0) | .value |= keys)' | jq -r 'to_entries[] | .key as $type | .value[] | . as $plugin | "PAGER=cat ansible-doc -t \($type) \($plugin)"' | tee "$script"
-    set -x
-    . "$script"
+    failed_commands=()
+    cat "$script" | while IFS= read -r cmd; do
+        echo -e "\e[0Ksection_start:`date +%s`:$cmd[collapsed=true]\r\e[0K$cmd"
+        exec "$cmd" || failed_commands+=("$cmd")
+        echo -e "\e[0Ksection_end:`date +%s`:$cmd\r\e[0K"
+    done
+    if [ ${#failed_commands[@]} -gt 0 ]; then
+        echo -e '\e[31m' # red
+        echo 'commands failed:'
+        for cmd in "${failed_commands[@]}"; do
+            echo '- `'"$cmd"'`'
+        done
+        echo -e '\e[0m'
+        exit 1
+    fi
 
 build-ci-container:
   when: manual
