Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,44 +13,42 @@ todos_fixmes:
     expire_in: 1 week
 ansible_test_integration:
   image: python:3.12-alpine
-  script:
-    - set -eo pipefail
-    - |
-      trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
-    - apk add git openssh-keygen bash uv
-    - uv pip install --system -r requirements.txt
-    - old_path="$PWD"
-    - tmpdir="$(mktemp -d)"
-    - trap "rm -rf '$tmpdir'" EXIT
-    - mkdir -p "$tmpdir/ansible_collections/unity"
-    - mv "$old_path" "$tmpdir/ansible_collections/unity/general"
-    - cd "$tmpdir/ansible_collections/unity/general"
-    - ansible-galaxy collection install ansible.posix community.general
-    - rc=0
-    - for target_path in tests/integration/targets/*; do
-    -     target="$(basename "$target_path")"
-    -     if [ "$target" == "callback" ]; then
-    -         continue
-    -     fi
-    -     ansible-test integration --color --diff "$target" || rc="$?"
-    - done
-    - exit "$rc"
+  script: |
+    set -eo pipefail
+    trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+    apk add git openssh-keygen bash uv
+    uv pip install --system -r requirements.txt
+    old_path="$PWD"
+    tmpdir="$(mktemp -d)"
+    trap "rm -rf '$tmpdir'" EXIT
+    mkdir -p "$tmpdir/ansible_collections/unity"
+    mv "$old_path" "$tmpdir/ansible_collections/unity/general"
+    cd "$tmpdir/ansible_collections/unity/general"
+    ansible-galaxy collection install ansible.posix community.general
+    rc=0
+    for target_path in tests/integration/targets/*; do
+        target="$(basename "$target_path")"
+        if [ "$target" == "callback" ]; then
+            continue
+        fi
+        ansible-test integration --color --diff "$target" || rc="$?"
+    done
+    exit "$rc"
 documentation:
   image: python:3.12-alpine
-  script:
-    - set -eo pipefail
-    - |
-      trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
-    - apk add git openssh-keygen bash uv jq
-    - uv pip install --system -r requirements.txt
-    - old_path="$PWD"
-    - tmpdir="$(mktemp -d)"
-    - script="$(mktemp)"
-    - trap "rm -rf '$tmpdir' '$script'" EXIT
-    - mkdir -p "$tmpdir/collections/ansible_collections/unity"
-    - mv "$old_path" "$tmpdir/collections/ansible_collections/unity/general"
-    - cd "$tmpdir"
-    - export ANSIBLE_COLLECTIONS_PATH="$tmpdir/collections"
-    - ansible-doc --metadata-dump unity.general | jq '.all | with_entries(select(.key != "keyword" and (.value | keys | length) > 0) | .value |= keys)' | jq -r 'to_entries[] | .key as $type | .value[] | . as $plugin | "PAGER=cat ansible-doc -t \($type) \($plugin)"' | tee "$script"
-    - set -x
-    - . "$script"
+  script: |
+    set -eo pipefail
+    trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+    apk add git openssh-keygen bash uv jq
+    uv pip install --system -r requirements.txt
+    old_path="$PWD"
+    tmpdir="$(mktemp -d)"
+    script="$(mktemp)"
+    trap "rm -rf '$tmpdir' '$script'" EXIT
+    mkdir -p "$tmpdir/collections/ansible_collections/unity"
+    mv "$old_path" "$tmpdir/collections/ansible_collections/unity/general"
+    cd "$tmpdir"
+    export ANSIBLE_COLLECTIONS_PATH="$tmpdir/collections"
+    ansible-doc --metadata-dump unity.general | jq '.all | with_entries(select(.key != "keyword" and (.value | keys | length) > 0) | .value |= keys)' | jq -r 'to_entries[] | .key as $type | .value[] | . as $plugin | "PAGER=cat ansible-doc -t \($type) \($plugin)"' | tee "$script"
+    set -x
+    . "$script"
