print which targets failed

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,7 +23,7 @@ ansible_test_integration:
     mv "$old_path" "$tmpdir/ansible_collections/unity/general"
     cd "$tmpdir/ansible_collections/unity/general"
     ansible-galaxy collection install ansible.posix community.general
-    rc=0
+    failed_targets=()
     for target_path in tests/integration/targets/*; do
         target="$(basename "$target_path")"
         if [ "$target" == "callback" ]; then
@@ -31,10 +31,13 @@ ansible_test_integration:
         fi
         # https://docs.gitlab.com/ci/jobs/job_logs/#custom-collapsible-sections
         echo -e "\e[0Ksection_start:`date +%s`:$target\r\e[0K$target"
-        ansible-test integration --color --diff "$target" || rc="$?"
+        ansible-test integration --color --diff "$target" || failed_targets+=("$target")
         echo -e "\e[0Ksection_end:`date +%s`:$target\r\e[0K"
     done
-    exit "$rc"
+    if [ ${#failed_targets[@]} -gt 0 ]; then
+        printf 'targets failed: '
+        printf -v joined '%s,' "${data[@]}"
+    fi
 documentation:
   image: registry.rc.umass.edu:5050/unity/ansible-collections/general
   script: |
